# Generated by Django 3.1 on 2021-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(default='Bishkek', max_length=100),
            preserve_default=False,
        ),
    ]
